version: "3"

services:

  timeshift:
    build:
      context: ./
      dockerfile: Dockerfile_TimeShift
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports: 
      - ${SERVER_PORT_NODE}:${SERVER_PORT}
    restart: "always"
    depends_on:
      - db
    volumes:
      - timeshift_files:${TS_FILES}

  streamdownloader:
    build:
      context: ./
      dockerfile: Dockerfile_StreamDownloader
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: "always"
    depends_on:
      - db
    volumes:
      - timeshift_files:${TS_FILES}

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - timeshift_db_data:${PGDATA}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT_NODE}:8080
    depends_on:
      - db
volumes:
  timeshift_db_data:
  timeshift_files: