version: "3"

services:

  app:
    build:
      context: ./
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports: 
      - ${SERVER_PORT_NODE}:${SERVER_PORT}
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:${PGDATA}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT_NODE}:8080
    depends_on:
      - db
