swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  - text/plain
paths:
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /timeShift/channels:
    # binds a127 app logic to a route
    x-swagger-router-controller: timeShift
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: getChannelFromTo
      parameters:
        - name: channelId
          in: query
          description: Id of wanted channel
          required: false
          type: string
        - name: from
          in: query
          description: Start point for downloading
          required: false
          type: string
        - name: to
          in: query
          description: End point for downloading
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /timeShift/variant:
    # binds a127 app logic to a route
    x-swagger-router-controller: timeShift
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: getSelectedVariantFromTo
      parameters:
        - name: variantId
          in: query
          description: Id of wanted variant
          required: false
          type: string
        - name: from
          in: query
          description: requested recording start point
          required: false
          type: string
        - name: to
          in: query
          description: requested recording end point
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /channels:
    # binds a127 app logic to a route
    x-swagger-router-controller: channel
    get:
      description: Returns specified channel to the caller
      # used as the method name of the controller
      operationId: getChannel
      parameters:
        - name: channelId
          in: query
          description: The channel id that is used for downloading
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            type: string
         
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete channel with specified id
      # used as the method name of the controller
      operationId: deleteChannel
      parameters:
        - name: id
          in: query
          description: Id of the channel we are trying to delete
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema: {}
         
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Adds a channel
      # used as the method name of the controller
      operationId: addChannel
      parameters:
        - name: uri
          in: formData
          description: The uri of the channel 
          required: false
          type: string
        - name: number_failed
          in: formData
          description: The number of failed chunks for that channel
          required: false
          type: string
        - name: number_succeded
          in: formData
          description: The number of succeded chunks for this channel
          required: false
          type: string
        - name: hours_to_record
          in: formData
          description: How many hours this channel should be recorded
          required: false
          type: string
        - name: name
          in: formData
          description: Name of the channel
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema: {}
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /saved_chunks:
    # binds a127 app logic to a route
    x-swagger-router-controller: saved_chunks
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: getChunk
      parameters:
        - name: id
          in: query
          description: The id of the chunk 
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema: {}
         
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: addChunk
      parameters:
        - name: variant_id
          in: formData
          description: The id of variant 
          required: true
          type: integer
        - name: filepath
          in: formData
          description: The filepath
          required: true
          type: string
        - name: duration
          in: formData
          description: Duration of the chunk
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema: {}
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Delete channel with specified id
      # used as the method name of the controller
      operationId: deleteSavedChunk
      parameters:
        - name: id
          in: query
          description: Id of the saved chunk
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema: {}
         
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /variants:
    x-swagger-router-controller: variants
    get:
      description: Returns the list of variants belonging to a channel
      operationId: getVariants
      parameters:
        - name: channel_id
          in: query
          description: The id of the channel
          required: true
          type: integer
      responses:
        "200":
          description: Success
          schema: {}
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    post:
      description: Add a new variant to a channel
      operationId: addVariant
      parameters:
        - name: channel_id
          in: formData
          description: The id of the channel
          required: true
          type: integer
        - name: uri
          in: formData
          description: URI of the media playlist for this variant
          required: true
          type: string
          format: uri
        - name: bandwidth
          in: formData
          description: The bandwidth in bits per second for this variant
          required: true
          type: integer
        - name: codecs
          in: formData
          type: string
          description: The codecs for this variant
      responses:
        "200":
          description: Success
          schema: {}
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Control whether the variant is disabled
      # used as the method name of the controller
      operationId: updateVariantFlag
      parameters:
        - name: id
          in: formData
          description: The id of the chunk 
          required: true
          type: integer
        - name: disabled
          in: formData
          description: If true the variant will be disabled. (not downloaded)
          required: false
          type: boolean
      responses:
        "200":
          description: Success
          schema: {}
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
